module.exports = {
  extends: ['eslint:recommended'],
  rules: {
    indent: ['error', 2],
    quotes: [
      'error',
      'single',
      {
        allowTemplateLiterals: false,
        avoidEscape: true,
      },
    ],
    semi: ['error', 'always'],
    'semi-spacing': 'error',
    'object-curly-spacing': ['error', 'always'],
    'object-curly-newline': ['error', {
      multiline: true,
      consistent: true
    }],
    'no-multiple-empty-lines': ['error', {
      max: 1,
      maxEOF: 1
    }],
    'operator-linebreak': ['error', 'before'],
    'quote-props': ['error', 'as-needed'],
    'no-trailing-spaces': 'warn',
    'no-multi-spaces': 'error',
    'no-mixed-operators': 'error',
    'no-nested-ternary': ['warn'],
    'no-var': 'error',
    camelcase: 'warn',
    'eol-last': ['error', 'always'],
    'no-console': 'error',
    'no-else-return': 'error',
    'no-unreachable': 'error',
    'import/no-cycle': 'error',
    'dot-notation': 'error',
    'no-floating-decimal': 'error',
    'no-sequences': 'error',
    'array-bracket-spacing': 'error',
    'computed-property-spacing': ['error', 'never'],
    curly: 'error',
    'no-lonely-if': 'error',
    'no-unneeded-ternary': 'error',
    'one-var-declaration-per-line': 'error',
    'array-callback-return': 'off',
    'prefer-const': 'error',
    'no-unused-expressions': 'off',
    'no-prototype-builtins': 'off',
    'space-in-parens': ['error', 'never'],
    'space-before-function-paren': ['error', {
      anonymous: 'always', named: 'never',
    }],
    'newline-before-return': 'error',
    'keyword-spacing': ['error'],
    'space-before-blocks': ['error', 'always'],
    'brace-style': 'error',
  },
};
