name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project dependencies
        run: npm ci
      - name: Run linters
        run: |
          npm run lint:js
          npm run lint:css
          npm run type-check
